#!/usr/bin/env bash

# Directory for what-related files (logs, temp-files, ...).
WHAT=~/.what

# Directory for temporary/intermediate files.
WORK="$WHAT/work"
# Directory for intermediate WAVE files.
WAVE="$WORK/wav"
# Directory for temporary scaled/converted imaged.
IMAGE="$WORK/img"
# For compiling releases before exporting to another hierarchy or watch directory.
OUTGOING="$WORK/outgoing"

# A directory for saving a release for later (putting it on ice) in case a coding 
# error keeps a workflow from completing.
ICE="$WHAT/ice"
# A directory for saving the release (artist, title, year) that is being worked on.
CONTEXT="$WHAT/context"

[[ -d $WHAT ]] || mkdir $WHAT

[[ -d $WORK ]] || mkdir $WORK
[[ -d $WAVE ]] || mkdir $WAVE
[[ -d $IMAGE ]] || mkdir $IMAGE
[[ -d $OUTGOING ]] || mkdir $OUTGOING

[[ -d $ICE ]] || mkdir $ICE
[[ -d $CONTEXT ]] || mkdir $CONTEXT

WHATRC=~/.whatrc
DIST_WHATRC="whatrc"
WHATRC_INSTALLED=<<EODIRECTIONS
Before installing, please take time to costumise your configuration.  Edit the
newly created file '~/.whatrc' and fill in any settings you want. You need to
add a correct Discogs.com API key in order to run the install tests.

After you have configured your '~/.whatrc' file, run the commands
 
    perl Makefile.PL
    make
    make test
    sudo make install

or

    perl Makefile.PL PREFIX=~/local/install/path
    make
    make test
    make install

See 'INSTALL' for more information.
EODIRECTIONS

if [[ ! -e $WHATRC ]]; then
    cp $DIST_WHATRC $WHATRC
    echo $WHATRC_INSTALLED
fi
