#!/usr/bin/env perl
#
# THIS SCRIPT HAS SERIOUS PROBLEMS, DOES NOT WORK CORRECTLY, 
# IS NOT IN THE MKRELEASE WORKFLOW, AND IS NOT INSTALLED.

# There are issues with the encodings used in filenames.
# For example the slash character '/' is searched for, 
#   but there is a fatter unicode slash (often used by XLD) 
#   that is totally missed and unchecked. 
# Until this is fixed, 
# searching for illegal chars will continue to work incorrectly.
# Replacing illegal chars will still be postponed until after 
#   all illegal chars can be found.

# Use perldoc or option --man to read documentation

########################################################################
# MODULES
########################################################################

# Include core modules.
use strict;
use warnings;
use File::Basename;
use Carp;

# Include CPAN modules.
use Getopt::Euclid qw{ :vars<opt_> };
use Readonly;

# Include private modules.
use What::WhatRC;


########################################################################
# GENERAL GLOBAL VARIABLES
########################################################################

# Basic program information.
Readonly my $prog_incantation  => $0;
Readonly my $prog_dir          => dirname($0);
Readonly my $prog_name         => basename($0);

# Command-line option hash.
my %opt = %ARGV;

# Global program exitcode.
my $exitcode = 0;

########################################################################
# PROGRAM SPECIFIC GLOBALS
########################################################################

my $illegal_chars = qr{([/?:])}xms;
my %replacement = (
    '/' => '[slash]',
    '?' => '[question]',
    ':' => '[colon]',);
my $whatrc = What::WhatRC->new('~/.whatrc');

########################################################################
# MAIN FUNCTION
########################################################################

# main() - main program execution 
sub main{
    exit($exitcode);
}

########################################################################
# SUPPORTING SUBROUTINES
########################################################################

sub has_illegals { $_[0] =~ $illegal_chars; }

sub illegals_replaced {
    my $s = shift;
    $s =~ s/$illegal_chars/$replacement{$1}/gexms;
    return $s;
}

sub fix_file {
    my $path = shift;
    my $fixed = illegals_replaced($path);
    return if ($fixed eq $path);
    croak("Destination file exists. $fixed ") if -e  $fixed;
}

sub fix_cue {
    my $cue_path = shift;

    open my $cue, "<", $cue_path
        or croak("Couldn't open $cue");

    my @cue = <$cue>;

    for (@cue) { 
        $_ = illegals_replaced($_) 
            if $_ =~ m/\A
                \s* FILE \s+ " (?: [^"] | \\" )* .wav" \s+ WAVE \s* \n? 
                \z/xms}

    close $cue;

    open $cue, ">", $cue_path;

    print {$cue} @cue;

    close $cue;
}

# Finally, kickstart the script
main();

__END__

=head1 NAME

release-rm-badchar
-- short description

=head1 VERSION

Version 0.0_1
Originally created on 08/10/10 00:14:05

=head1 USAGE

release-rm-badchar [options]

=head1 REQUIRED ARGUMENTS

=over

=back

=head1 OPTIONS

=over

=item --version

=item --usage

=item --help

=item --man

Print the usual program information

=back

=head1 DESCRIPTION

This does not work, is not called by any other program, and should
not be called by the user.

=head1 BUGS

=over

=back

=head1 COPYRIGHT & LICENSE

©Bryan Matsuo (bryan.matsuo@gmail.com)

This file is part of What.

What is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

What is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with What.  If not, see <http://www.gnu.org/licenses/>.

=cut
