#!/usr/bin/env perl

# Use perldoc or option --man to read documentation

########################################################################
# MODULES
########################################################################

# Include core modules.
use strict;
use warnings;
use File::Basename;
use Carp;

# Include CPAN modules.
use Getopt::Euclid qw{ :vars<opt_> };
use Readonly;

# Include private modules.
use What::WhatRC;
use What::Release;

our $VERSION = '0.0_1';

########################################################################
# GENERAL GLOBAL VARIABLES
########################################################################

# Basic program information.
Readonly my $prog_incantation  => $0;
Readonly my $prog_dir          => dirname($0);
Readonly my $prog_name         => basename($0);

# Command-line option hash.
my %opt = %ARGV;

# Global program exitcode.
my $exitcode = 0;

########################################################################
# PROGRAM SPECIFIC GLOBALS
########################################################################

# Read whatrc file
my $whatrc = read_whatrc("~/.whatrc");

########################################################################
# MAIN FUNCTION
########################################################################

# main() - main program execution 
sub main{
    my ($artist, $year, $title) 
        = map {$opt{$_}} qw{--artist --year --title};
    my $num_discs = $opt{"--num-discs"};

    my $release = What::Release->new(
        rip_root => $whatrc->{upload_root},
        artist => $opt{'--artist'},
        title => $opt{'--title'},
        year => $opt{'--year'},
        discs => $opt{'--num-discs'});

    my $rip_root = $whatrc->{upload_root};

    my $artist_path = $release->artist_dir($rip_root);
    my $root_path = $release->dir($rip_root);
    my $flac_dir_path = $release->format_dir($rip_root, 'flac');

    my @mkartist = ('mkdir', $artist_path);
    my @mkroot = ('mkdir', $root_path);
    my @mkflac = ('mkdir', $flac_dir_path);

    # Don't check exit code because failure is tolerable
    subsystem(@mkartist) == 0
        or croak("Couldn't make artist directory $artist_path")
            if !-d $artist_path;

    subsystem(@mkroot) == 0
        or croak("Couldn't make root directory $root_path");

    subsystem(@mkflac) == 0
        or croak("Couldn't make FLAC directory $flac_dir_path");

    if ($num_discs > 1) {
        for my $disc (1 .. $num_discs) {
            my $disc_dir = "$flac_dir_path/CD$disc";
            my @mkdisc = ('mkdir', $disc_dir);
            subsystem(@mkdisc) == 0
                or croak("Couldn't make CD$disc directory.");
        }
    }

    exit($exitcode);
}

########################################################################
# SUPPORTING SUBROUTINES
########################################################################

sub subsystem {
    if ($opt{'--verbose'} or $opt{'--dry-run'}) {
        print "@_\n"
    }
    if (not $opt{'--dry-run'}) {
        return system @_;
    }
    return 0;
}

# Finally, kickstart the script
main();

__END__

=head1 NAME

album-scaffold
-- short description

=head1 VERSION

Version 0.0_1
Originally created on 07/07/10 23:48:39

=head1 USAGE

album-scaffold [options]

=head1 REQUIRED ARGUMENTS

=over

=back

=head1 OPTIONS

=over

=item --artist [=] <artist>

Album artist

for Euclid:
    artist.type: string, -z artist
    artist.default: 'artist'

=item --title [=] <title>

Album name

for Euclid:
    title.type: string, -z album
    title.default: 'album'

=item --year [=] <year>

Album release year

=for Euclid:
    year.type: /[0-9]{4}/

=item --num-discs [=] <discs>

Number of discs in release.

=for Euclid:
    discs.type: +integer
    discs.default: 1

=item --dry-run

Don't actually make changes to the filesystem. 
Just print the steps being taken by album-scaffold.

=item --verbose

Print out the steps being taken by album-scaffold before they are
executed.

=item --version

=item --usage

=item --help

=item --man

Print the usual program information

=back

=head1 DESCRIPTION

=head1 BUGS

=over

=back

=head1 AUTHOR & COPYRIGHT 

©Bryan Matsuo (bryan.matsuo@gmail.com)

