#!/usr/bin/env perl

# Use perldoc or option --man to read documentation

########################################################################
# MODULES
########################################################################

# Include core modules.
use strict;
use warnings;
use File::Basename;
use Carp;

# Include CPAN modules.
use Getopt::Euclid qw{ :vars<opt_> };
use Readonly;

# Include private modules.
use What::Subsystem;
use What::WhatRC;
use What::Release;

########################################################################
# GENERAL GLOBAL VARIABLES
########################################################################

# Basic program information.
Readonly my $prog_incantation  => $0;
Readonly my $prog_dir          => dirname($0);
Readonly my $prog_name         => basename($0);

# Command-line option hash.
my %opt = %ARGV;

# Global program exitcode.
my $exitcode = 0;

########################################################################
# PROGRAM SPECIFIC GLOBALS
########################################################################

########################################################################
# MAIN FUNCTION
########################################################################

# main() - main program execution 
sub main{
    my $whatrc = read_whatrc("~/.whatrc");

    my $release = What::Release->new(
        rip_root => $whatrc->{upload_root},
        artist => $opt{'--artist'},
        title => $opt{'--title'},
        year => $opt{'--year'},);

    my $subsystem = What::Subsystem->new(
        dryrun=>$opt{'--dry-run'},
        verbose=>$opt{'--verbose'});

    my %want_format = (
        'V0'    => $opt{'--v0'},
        'V2'    => $opt{'--v2'},
        '320'   => $opt{'--320'},
        'FLAC'  => $opt{'--flac'},
        'OGG'  => $opt{'--ogg'},
        'AAC'  => $opt{'--aac'},
    );

    my $announce = $whatrc->announce();

    for my $format (keys %want_format) {
        next if not $want_format{$format};

        my $format_dir 
            = $release->format_dir($whatrc->{upload_root}, $format);

        my @mktorrent_cmd = mktorrent_command(
            announce    => $announce,
            source_dir  => $format_dir,);

        $subsystem->exec(@mktorrent_cmd) == 0
            or croak("Couldn't create torrent file.");
    }

    exit($exitcode);
}

########################################################################
# SUPPORTING SUBROUTINES
########################################################################

# Subroutine: mktorrent_options(
#   announce => $url,
#   source_dir => $src_path)
# Type: INTERNAL UTILITY
# Purpose: Construct a list of options for mktorrent.
# Returns: A list of options.
sub mktorrent_options {
    my %arg = @_;
    my ($url, $src_path) = ($arg{announce}, $arg{source_dir});

    # Remove a trailing '/' from the directory being used.
    $src_path =~ s!(.)/\z!$1!xms;

    my $torrent_path = "$src_path.torrent";

    my @options = ('-p', '-a', $url, '-o', $torrent_path);

    return @options;
}

# Subroutine: 
#   mktorrent_command(
#       announce => $url,
#       source_dir => $src_path,)
# Type: INTERFACE SUB
# Purpose: Construct a system command that will create a 
# Returns: A list representation of the system command.
sub mktorrent_command {
    my %arg = @_;

    croak("Announce URL is not specified.")
        if not $arg{announce};
    croak("Torrent source is not specified.")
        if not $arg{source_dir};

    my @options = mktorrent_options(%arg);

    my @cmd = ('mktorrent', @options, $arg{source_dir});

    return @cmd;
}

# Finally, kickstart the script
main();

__END__

=head1 NAME

mktorrent-release
-- short description

=head1 VERSION

Version 0.0_1
Originally created on 07/16/10 03:41:08

=head1 USAGE

mktorrent-release [options]

=head1 REQUIRED ARGUMENTS

=over

=item --artist <artist>

Release artist.

=for Euclid:
    artist.type: -z artist

=item --title <title>

=for Euclid:
    title.type: -z title 

Release title.

=item --year <year>

Release year.

=for Euclid:
    year.type: /\d{4}/

=back

=head1 OPTIONS

=over

=item --v0 | --V0

Create an MP3 V0 VBR torrent.

=item --v2 | --V2

Create an MP3 V2 VBR torrent.

=item --320

Create an MP3 320kbps CBR torrent.

=item --flac | --FLAC

Create a FLAC torrent.
FLAC files will be stored in the upload hierachy 
regardless of this option.

=item --ogg | --OGG | --q8

Create an OGG -q8.0 VBR torrent.

=item --aac | --AAC

Create an AAC ~256kbps ABR torrent.

=item --all

Create torrents for all present formats and bitrates (not working yet).

=item --dry-run

=item --verbose

=item --version

=item --usage

=item --help

=item --man

Print the usual program information

=back

=head1 DESCRIPTION

=head1 BUGS

=over

=back

=head1 COPYRIGHT & LICENSE

©Bryan Matsuo (bryan.matsuo@gmail.com)

This file is part of What.

What is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

What is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with What.  If not, see <http://www.gnu.org/licenses/>.

=cut
